-- Your SQL goes here
CREATE TABLE images (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  uid VARCHAR(255) NOT NULL,
  tid VARCHAR(255),
  height INT,
  width INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
